// Generated by `pnpm i18n:types` — do not edit.
// One entry per namespace, typed from that namespace's `en.json`:
// English is the source of truth for the key set. Other locales are checked
// against it by `diffMessageKeys()`, not by the type system.

declare module 'vue-i18n' {
  interface DefineLocaleMessage {
    dashboard: typeof import('../features/dashboard/i18n/en.json')
    finances: typeof import('../features/finances/i18n/en.json')
    instructors: typeof import('../features/instructors/i18n/en.json')
    planner: typeof import('../features/planner/i18n/en.json')
    school: typeof import('../features/school/i18n/en.json')
    shared: typeof import('../shared/i18n/en.json')
    students: typeof import('../features/students/i18n/en.json')
  }
}

export {}
