/**
 * Regenerates `src/i18n/locale-messages.generated.d.ts`, which is what makes
 * `t()` type-safe: it augments vue-i18n's `DefineLocaleMessage` with one entry
 * per namespace, typed from that namespace's `en.json`.
 *
 * Run by the Vite plugin in `vite.config.ts` (dev + build) and by
 * `pnpm i18n:types`. The output is committed so `vue-tsc` works standalone.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const SRC = fileURLToPath(new URL('../src/', import.meta.url))
const OUTPUT = join(SRC, 'i18n/locale-messages.generated.d.ts')
const SOURCE_LOCALE_FILE = 'en.json'

/** Directories that may own an `i18n/` folder, in namespace order. */
function messageOwners(): { namespace: string, dir: string }[] {
  const featuresDir = join(SRC, 'features')
  const features = readdirSync(featuresDir, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => ({ namespace: entry.name, dir: join(featuresDir, entry.name) }))

  return [{ namespace: 'shared', dir: join(SRC, 'shared') }, ...features]
    .filter(owner => existsMessageFile(owner.dir))
    .sort((a, b) => a.namespace.localeCompare(b.namespace))
}

function existsMessageFile(ownerDir: string): boolean {
  try {
    readdirSync(join(ownerDir, 'i18n'))
    return true
  }
  catch {
    return false
  }
}

function importPath(ownerDir: string): string {
  const path = relative(dirname(OUTPUT), join(ownerDir, 'i18n', SOURCE_LOCALE_FILE))
  return path.startsWith('.') ? path : `./${path}`
}

export function generateI18nTypes(): boolean {
  const entries = messageOwners()
    .map(owner => `    ${owner.namespace}: typeof import('${importPath(owner.dir)}')`)
    .join('\n')

  const contents = `// Generated by \`pnpm i18n:types\` — do not edit.
// One entry per namespace, typed from that namespace's \`${SOURCE_LOCALE_FILE}\`:
// English is the source of truth for the key set. Other locales are checked
// against it by \`diffMessageKeys()\`, not by the type system.

declare module 'vue-i18n' {
  interface DefineLocaleMessage {
${entries}
  }
}

export {}
`

  const previous = readFileSyncOrEmpty(OUTPUT)
  if (previous === contents)
    return false

  writeFileSync(OUTPUT, contents)
  return true
}

function readFileSyncOrEmpty(path: string): string {
  try {
    return readFileSync(path, 'utf8')
  }
  catch {
    return ''
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const changed = generateI18nTypes()
  console.log(`[i18n] ${relative(process.cwd(), OUTPUT)} ${changed ? 'updated' : 'already up to date'}`)
}
